var hierarchy =
[
    [ "ActionBasedContinuousMoveProvider", null, [
      [ "UnityEngine.XR.Interaction.Toolkit.Samples.StarterAssets.DynamicMoveProvider", "class_unity_engine_1_1_x_r_1_1_interaction_1_1_toolkit_1_1_samples_1_1_starter_assets_1_1_dynamic_move_provider.html", null ]
    ] ],
    [ "AudioController", "class_audio_controller.html", null ],
    [ "ViveSR.anipal.Eye.CombinedEyeData", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_combined_eye_data.html", null ],
    [ "ViveSR.anipal.Eye.EyeData", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_eye_data.html", null ],
    [ "ViveSR.anipal.Eye.EyeData_v2", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_eye_data__v2.html", null ],
    [ "ViveSR.anipal.Eye.EyeExpression", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_eye_expression.html", null ],
    [ "ViveSR.anipal.Eye.EyeParameter", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_eye_parameter.html", null ],
    [ "ViveSR.anipal.Eye.EyeShapeTable", "class_vive_s_r_1_1anipal_1_1_eye_1_1_eye_shape_table.html", null ],
    [ "ViveSR.anipal.Eye.EyeShapeTable_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_eye_shape_table__v2.html", null ],
    [ "ViveSR.anipal.Eye.FocusInfo", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_focus_info.html", null ],
    [ "ViveSR.anipal.Eye.GazeRayParameter", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_gaze_ray_parameter.html", null ],
    [ "IGazeFocusable", null, [
      [ "Tobii.XR.Examples.DevTools.HighlightAtGaze", "class_tobii_1_1_x_r_1_1_examples_1_1_dev_tools_1_1_highlight_at_gaze.html", null ],
      [ "Tobii.XR.Examples.GettingStarted.HighlightAtGaze", "class_tobii_1_1_x_r_1_1_examples_1_1_getting_started_1_1_highlight_at_gaze.html", null ]
    ] ],
    [ "IPointerClickHandler", null, [
      [ "TMPro.Examples.TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "TMPro.Examples.TMP_TextSelector_A", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___a.html", null ],
      [ "TMPro.Examples.TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ],
      [ "TMPro.TMP_TextEventHandler", "class_t_m_pro_1_1_t_m_p___text_event_handler.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "TMPro.Examples.TMP_TextSelector_A", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___a.html", null ],
      [ "TMPro.Examples.TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ],
      [ "TMPro.TMP_TextEventHandler", "class_t_m_pro_1_1_t_m_p___text_event_handler.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "TMPro.Examples.TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ]
    ] ],
    [ "ViveSR.anipal.Lip.LipData", "struct_vive_s_r_1_1anipal_1_1_lip_1_1_lip_data.html", null ],
    [ "ViveSR.anipal.Lip.LipData_v2", "struct_vive_s_r_1_1anipal_1_1_lip_1_1_lip_data__v2.html", null ],
    [ "ViveSR.anipal.Lip.LipShapeTable", "class_vive_s_r_1_1anipal_1_1_lip_1_1_lip_shape_table.html", null ],
    [ "ViveSR.anipal.Lip.LipShapeTable_v2", "class_vive_s_r_1_1anipal_1_1_lip_1_1_lip_shape_table__v2.html", null ],
    [ "LocomotionProvider", null, [
      [ "TunnelVisionAlwaysMove", "class_tunnel_vision_always_move.html", null ]
    ] ],
    [ "MonoBehaviour", null, [
      [ "BowlHandler", "class_bowl_handler.html", null ],
      [ "CabinetAudioController", "class_cabinet_audio_controller.html", null ],
      [ "CalibrateEye", "class_calibrate_eye.html", null ],
      [ "ChangeScene", "class_change_scene.html", null ],
      [ "ChatController", "class_chat_controller.html", null ],
      [ "Clock", "class_clock.html", null ],
      [ "DropdownSample", "class_dropdown_sample.html", null ],
      [ "EnvMapAnimator", "class_env_map_animator.html", null ],
      [ "EventSystemHandler", "class_event_system_handler.html", null ],
      [ "EyeTrackingTest", "class_eye_tracking_test.html", null ],
      [ "HandAnimationHallway", "class_hand_animation_hallway.html", null ],
      [ "HandPresence", "class_hand_presence.html", null ],
      [ "HideContainerContent", "class_hide_container_content.html", null ],
      [ "LiquidHeightLevel", "class_liquid_height_level.html", null ],
      [ "OvenLightController", "class_oven_light_controller.html", null ],
      [ "PhoneAudio", "class_phone_audio.html", null ],
      [ "PhoneFlickerButton", "class_phone_flicker_button.html", null ],
      [ "PizzaDone", "class_pizza_done.html", null ],
      [ "PizzaInOrder", "class_pizza_in_order.html", null ],
      [ "PointOrOpen", "class_point_or_open.html", null ],
      [ "PreviewDisabler", "class_preview_disabler.html", null ],
      [ "SojaExiles.Drawer_Pull_X", "class_soja_exiles_1_1_drawer___pull___x.html", null ],
      [ "SojaExiles.Drawer_Pull_Z", "class_soja_exiles_1_1_drawer___pull___z.html", null ],
      [ "SojaExiles.MouseLook", "class_soja_exiles_1_1_mouse_look.html", null ],
      [ "SojaExiles.PlayerMovement", "class_soja_exiles_1_1_player_movement.html", null ],
      [ "SojaExiles.Quitgame", "class_soja_exiles_1_1_quitgame.html", null ],
      [ "SojaExiles.SceneSwitchGen", "class_soja_exiles_1_1_scene_switch_gen.html", null ],
      [ "SojaExiles.opencloseDoor", "class_soja_exiles_1_1openclose_door.html", null ],
      [ "SojaExiles.opencloseDoor1", "class_soja_exiles_1_1openclose_door1.html", null ],
      [ "SojaExiles.opencloseStallDoor", "class_soja_exiles_1_1openclose_stall_door.html", null ],
      [ "SojaExiles.opencloseWindow", "class_soja_exiles_1_1openclose_window.html", null ],
      [ "SojaExiles.opencloseWindow1", "class_soja_exiles_1_1openclose_window1.html", null ],
      [ "StartAudio", "class_start_audio.html", null ],
      [ "TMPro.Examples.Benchmark01", "class_t_m_pro_1_1_examples_1_1_benchmark01.html", null ],
      [ "TMPro.Examples.Benchmark01_UGUI", "class_t_m_pro_1_1_examples_1_1_benchmark01___u_g_u_i.html", null ],
      [ "TMPro.Examples.Benchmark02", "class_t_m_pro_1_1_examples_1_1_benchmark02.html", null ],
      [ "TMPro.Examples.Benchmark03", "class_t_m_pro_1_1_examples_1_1_benchmark03.html", null ],
      [ "TMPro.Examples.Benchmark04", "class_t_m_pro_1_1_examples_1_1_benchmark04.html", null ],
      [ "TMPro.Examples.CameraController", "class_t_m_pro_1_1_examples_1_1_camera_controller.html", null ],
      [ "TMPro.Examples.ObjectSpin", "class_t_m_pro_1_1_examples_1_1_object_spin.html", null ],
      [ "TMPro.Examples.ShaderPropAnimator", "class_t_m_pro_1_1_examples_1_1_shader_prop_animator.html", null ],
      [ "TMPro.Examples.SimpleScript", "class_t_m_pro_1_1_examples_1_1_simple_script.html", null ],
      [ "TMPro.Examples.SkewTextExample", "class_t_m_pro_1_1_examples_1_1_skew_text_example.html", null ],
      [ "TMPro.Examples.TMP_ExampleScript_01", "class_t_m_pro_1_1_examples_1_1_t_m_p___example_script__01.html", null ],
      [ "TMPro.Examples.TMP_FrameRateCounter", "class_t_m_pro_1_1_examples_1_1_t_m_p___frame_rate_counter.html", null ],
      [ "TMPro.Examples.TMP_TextEventCheck", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_event_check.html", null ],
      [ "TMPro.Examples.TMP_TextInfoDebugTool", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_info_debug_tool.html", null ],
      [ "TMPro.Examples.TMP_TextSelector_A", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___a.html", null ],
      [ "TMPro.Examples.TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ],
      [ "TMPro.Examples.TMP_UiFrameRateCounter", "class_t_m_pro_1_1_examples_1_1_t_m_p___ui_frame_rate_counter.html", null ],
      [ "TMPro.Examples.TMPro_InstructionOverlay", "class_t_m_pro_1_1_examples_1_1_t_m_pro___instruction_overlay.html", null ],
      [ "TMPro.Examples.TeleType", "class_t_m_pro_1_1_examples_1_1_tele_type.html", null ],
      [ "TMPro.Examples.TextConsoleSimulator", "class_t_m_pro_1_1_examples_1_1_text_console_simulator.html", null ],
      [ "TMPro.Examples.TextMeshProFloatingText", "class_t_m_pro_1_1_examples_1_1_text_mesh_pro_floating_text.html", null ],
      [ "TMPro.Examples.TextMeshSpawner", "class_t_m_pro_1_1_examples_1_1_text_mesh_spawner.html", null ],
      [ "TMPro.Examples.VertexColorCycler", "class_t_m_pro_1_1_examples_1_1_vertex_color_cycler.html", null ],
      [ "TMPro.Examples.VertexJitter", "class_t_m_pro_1_1_examples_1_1_vertex_jitter.html", null ],
      [ "TMPro.Examples.VertexShakeA", "class_t_m_pro_1_1_examples_1_1_vertex_shake_a.html", null ],
      [ "TMPro.Examples.VertexShakeB", "class_t_m_pro_1_1_examples_1_1_vertex_shake_b.html", null ],
      [ "TMPro.Examples.VertexZoom", "class_t_m_pro_1_1_examples_1_1_vertex_zoom.html", null ],
      [ "TMPro.Examples.WarpTextExample", "class_t_m_pro_1_1_examples_1_1_warp_text_example.html", null ],
      [ "TMPro.TMP_TextEventHandler", "class_t_m_pro_1_1_t_m_p___text_event_handler.html", null ],
      [ "Tobii.XR.Examples.DevTools.HighlightAtGaze", "class_tobii_1_1_x_r_1_1_examples_1_1_dev_tools_1_1_highlight_at_gaze.html", null ],
      [ "Tobii.XR.Examples.DevTools.SimpleMovement", "class_tobii_1_1_x_r_1_1_examples_1_1_dev_tools_1_1_simple_movement.html", null ],
      [ "Tobii.XR.Examples.DevTools.SimpleRotation", "class_tobii_1_1_x_r_1_1_examples_1_1_dev_tools_1_1_simple_rotation.html", null ],
      [ "Tobii.XR.Examples.DevTools.SimpleScaling", "class_tobii_1_1_x_r_1_1_examples_1_1_dev_tools_1_1_simple_scaling.html", null ],
      [ "Tobii.XR.Examples.GettingStarted.HighlightAtGaze", "class_tobii_1_1_x_r_1_1_examples_1_1_getting_started_1_1_highlight_at_gaze.html", null ],
      [ "TunnelVisionLookAt", "class_tunnel_vision_look_at.html", null ],
      [ "TunnelVisionStrenght", "class_tunnel_vision_strenght.html", null ],
      [ "UIButtons", "class_u_i_buttons.html", null ],
      [ "UnityEngine.XR.Interaction.Toolkit.Samples.StarterAssets.ActionBasedControllerManager", "class_unity_engine_1_1_x_r_1_1_interaction_1_1_toolkit_1_1_samples_1_1_starter_assets_1_1_action_based_controller_manager.html", null ],
      [ "ViveSR.anipal.Eye.DartBoard", "class_vive_s_r_1_1anipal_1_1_eye_1_1_dart_board.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_AvatarEyeSample", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___avatar_eye_sample.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_AvatarEyeSample_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___avatar_eye_sample__v2.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_EyeFocusSample", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye_focus_sample.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_EyeFocusSample_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye_focus_sample__v2.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_EyeSettingSample", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye_setting_sample.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_Eye_Framework", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye___framework.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_GazeRaySample", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___gaze_ray_sample.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_GazeRaySample_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___gaze_ray_sample__v2.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_MirrorCameraSample_Eye", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___mirror_camera_sample___eye.html", null ],
      [ "ViveSR.anipal.Eye.SRanipal_MirrorCameraSample_Eye_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___mirror_camera_sample___eye__v2.html", null ],
      [ "ViveSR.anipal.Lip.SRanipal_AvatarLipSample", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___avatar_lip_sample.html", null ],
      [ "ViveSR.anipal.Lip.SRanipal_AvatarLipSample_v2", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___avatar_lip_sample__v2.html", null ],
      [ "ViveSR.anipal.Lip.SRanipal_Lip_Framework", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___lip___framework.html", null ],
      [ "ViveSR.anipal.Lip.SRanipal_MirrorCameraSample_Lip", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___mirror_camera_sample___lip.html", null ],
      [ "Wobble", "class_wobble.html", null ]
    ] ],
    [ "ViveSR.anipal.Lip.PredictionData", "struct_vive_s_r_1_1anipal_1_1_lip_1_1_prediction_data.html", null ],
    [ "ViveSR.anipal.Lip.PredictionData_v2", "struct_vive_s_r_1_1anipal_1_1_lip_1_1_prediction_data__v2.html", null ],
    [ "ViveSR.anipal.Eye.SingleEyeData", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_single_eye_data.html", null ],
    [ "ViveSR.anipal.Eye.SingleEyeExpression", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_single_eye_expression.html", null ],
    [ "ViveSR.anipal.SRanipal_API", "class_vive_s_r_1_1anipal_1_1_s_ranipal___a_p_i.html", null ],
    [ "ViveSR.anipal.Eye.SRanipal_Eye", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye.html", null ],
    [ "ViveSR.anipal.Eye.SRanipal_Eye_API", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye___a_p_i.html", null ],
    [ "ViveSR.anipal.Eye.SRanipal_Eye_v2", "class_vive_s_r_1_1anipal_1_1_eye_1_1_s_ranipal___eye__v2.html", null ],
    [ "ViveSR.anipal.Lip.SRanipal_Lip", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___lip.html", null ],
    [ "ViveSR.anipal.Lip.SRanipal_Lip_API", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___lip___a_p_i.html", null ],
    [ "ViveSR.anipal.Lip.SRanipal_Lip_v2", "class_vive_s_r_1_1anipal_1_1_lip_1_1_s_ranipal___lip__v2.html", null ],
    [ "TMP_InputValidator", null, [
      [ "TMPro.TMP_DigitValidator", "class_t_m_pro_1_1_t_m_p___digit_validator.html", null ],
      [ "TMPro.TMP_PhoneNumberValidator", "class_t_m_pro_1_1_t_m_p___phone_number_validator.html", null ]
    ] ],
    [ "ViveSR.anipal.Eye.TrackingImprovements", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_tracking_improvements.html", null ],
    [ "UnityEvent", null, [
      [ "TMPro.TMP_TextEventHandler.CharacterSelectionEvent", "class_t_m_pro_1_1_t_m_p___text_event_handler_1_1_character_selection_event.html", null ],
      [ "TMPro.TMP_TextEventHandler.LineSelectionEvent", "class_t_m_pro_1_1_t_m_p___text_event_handler_1_1_line_selection_event.html", null ],
      [ "TMPro.TMP_TextEventHandler.LinkSelectionEvent", "class_t_m_pro_1_1_t_m_p___text_event_handler_1_1_link_selection_event.html", null ],
      [ "TMPro.TMP_TextEventHandler.SpriteSelectionEvent", "class_t_m_pro_1_1_t_m_p___text_event_handler_1_1_sprite_selection_event.html", null ],
      [ "TMPro.TMP_TextEventHandler.WordSelectionEvent", "class_t_m_pro_1_1_t_m_p___text_event_handler_1_1_word_selection_event.html", null ]
    ] ],
    [ "ViveSR.anipal.Eye.VerboseData", "struct_vive_s_r_1_1anipal_1_1_eye_1_1_verbose_data.html", null ],
    [ "TMPro.Examples.VertexJitter.VertexAnim", "struct_t_m_pro_1_1_examples_1_1_vertex_jitter_1_1_vertex_anim.html", null ],
    [ "XRGrabInteractable", null, [
      [ "LeafHandler", "class_leaf_handler.html", null ]
    ] ]
];